### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by solarhell** [arxitics/ui-schema#1]
When in [fullpage example](http://arxitics.github.io/ui-schema/examples/full-pages.html), if i click the bottom button, 'ui-nav-pagination' 's li element doesn't change its 'ui-state-active' class actively.
FYI,i am using Chrome 53.0.2785.116

**Comment by photino** [comment]
是有这个问题，在那个示例中有两种导航方式：一个是底部的，一个是右边的`ui-nav-pagination`。区别在于：前者只能是手动点击的，不依赖于JS；后者除了手动点击还可以通过`data-schema-autoplay`设置自动播放，这是依赖于JS的，改变`ui-state-active`也得靠JS。当初实现的时候是考虑这两种导航方式在写页面时只选取一种就可以了，所以就没考虑你提到的这个问题。如果要修正也是可以的，只是不很清楚有没有这种必要，或许可以把这两种导航方式看成互相独立的。在右边这种自动播放的情形，改变`ui-state-active`是需要记录一个`index`值的，在目前的实现中，点击底部的导航并不会改变这个值，所以右边导航中的`ui-state-active`状态也不会改变，当你把鼠标不再hover底部的导航链接时，右边的导航会继续从原来的`index`开始自动播放，所以这两种导航方式在功能上是相互补充的。此外，[Carousel](http://arxitics.github.io/ui-schema/css/events.html)的自动播放和这里是共用相同的实现的，如果要改的话两处都要考虑

此外，如果需要实现fullpage效果可以参考我为AmazeUI写的另一个相似的插件[amazeui-fullpage](https://github.com/photino/amazeui-fullpage)，这个代码更简明清晰

**Comment by solarhell** [comment]
感谢回复 👍  已经用上了
