### ISSUE TITLE
事件绑定问题

### ISSUE THREAD

**Issue by lann1986** [arxitics/ui-schema#2]
你好，请问ui-schema事件绑定是怎么用的呢？
在todo例子中看到 data-schema-controller="add" 不太明白控制器是怎么用？是事件的接口？
：）
怎么在DOM元素绑定事件呢？

**Comment by photino** [comment]
这个controller是在触发Model和View更新时自动调用的，对于

```
<input data-schema-model="todo" data-schema-trigger="change" data-schema-controller="add">
```

`schema.add()`函数会在更新`todo`的值后调用；如果是这种

```
<div class="ui-content-alert" data-schema-view="message" data-schema-controller="encrypt"></div>
```

`schema.encrypt()`函数会在渲染视图之前调用，这里的`data-schema-view="message"`指定了该视图所依赖的model，当然也可以不指定，指定的好处是它在渲染之前会进行依赖检查看是否存在该model，也会检测该model的值是否发生变化从而决定是否重新渲染。所以`data-schema-controller`是指定了调用函数的名称，参数列表是`(models, $this)`，这里的`models`其实就是`shcema.models`，所有与视图相关的变量都保存在这个对象上。`data-schema-adapter`与`data-schema-controller`类似，只不过它的参数是`(model, $this)`。

在UI Schema中，所有的事件绑定都是通过Data API进行的，比如`data-schema-model`绑定的是`schema.observe()`，`data-schema-view`绑定的是`schema.render()`，所有的事件列表都会保存在`schema.events`这个对象上。自定义的事件可以通过`data-schema-event`来声明，比如

```
<thead data-schema-event="init selectall"></thead>
```

就声明了两个事件`schema.init()`和`schema.selectall()`，它们默认的选择器就是`[data-schema-init]`和`[data-schema-selectall]`，当然选择器也是可以通过`data-schema-selector`属性指定的。事件在加入`schema.events`列表中后会自动触发，也可以使用`schema.trigger()`手动触发。

**Comment by lann1986** [comment]
@photino 十分感谢能收到回复和解答。
`<li data-schema-event="init" data-schema-trigger="click">News</li>`
`schema.init = function (event, options){console.log("a");}`
通过 `data-schema-event`自定义事件，指定事件触发类型。怎么做呢？用JQ?

## 

我学习了W3School网站上的JavaScript教程，想看懂ui-schema-0.4.3.js需要再学习那些知识呢？

**Comment by photino** [comment]
@lann1986 使用`data-schema-event`自定义事件时，它只是说明了将把这个事件绑定到哪些DOM上，如何触发以及在什么时候触发需要自己控制。上面那段代码中`data-schema-trigger`是起不到作用的，绑定事件时`schema.init()`会自动调用，所以不需要再写任何其它的就已经有`console`输出了。

看一下这个例子

```
<ul data-schema-event="test">
   <li data-schema-test>News 1</li>
   <li>News 2</li>
   <li data-schema-test>News 3</li>
</ul>
<script>
  schema.test = function (event, options) {
    alert("test");
    $(schema.events.test.selector).on('click', function () {
      alert($(this).text());
    });
  }
</script>
```

属性`data-schema-event="test"`定义了`schema.test()`事件，默认绑定选择器为`[data-schema-test]`的DOM上，然后所有的DOM操作都要写在`schema.test()`函数中，比如点击显示文本。`data-schema-trigger`在这里用不到，在TodoMVC那个例子中它是用在`data-schema-model`来指定Model更新的触发类型。

UI Schema的事件处理方式主要是使用了jQuery的[Event Object](http://api.jquery.com/category/events/event-object/)，所以要求对jQuery非常熟悉。其它的部分也参考了Bootstrap和AngularJS，如果有一定的了解也会比较好。

**Comment by lann1986** [comment]
@photino :+1:  :)
大概明白怎么用了，十分感谢。

**Comment by lann1986** [comment]
：）还是我。嘿嘿。。
遇到一个新问题，还要再度麻烦大神了。。
如果这个设定了事件绑定的DOM在页面初始化时不存在，加载这个DOM时如何刷新事件绑定呢？
`schema.load()`? 是用这个吗？怎么用呢？

**Comment by photino** [comment]
@lann1986  使用`data-schema-event="test"`自定义一个事件`schema.test()`时，它默认是绑定到选择器`[data-schema-test]`上，这里实际上是有一个问题的：此时的选择器选的只是已经存在的DOM，对于动态生成的新的DOM，需要自己重新触发事件绑定，可以使用`schema.trigger('test')`，如果有时只想更新增加的DOM，可以再添加一个可选的参数`schema.trigger('test', $('new-added-dom'))`。当然，你再调用一次`schema.load()`也是可以的，但是它把所有的事件都重新绑定了一遍，这有点太浪费了。不知道有没有回答你的疑问？

**Comment by lann1986** [comment]
@photino ：）
好像我理解有问题...

```
<div data-schema-event="list">
    <ul>
        <li><a href="javascript:;" data-schema-list="">1#</a></li>
        <li><a href="javascript:;" data-schema-list="">2#</a></li>
        <li><a href="javascript:;" data-schema-list="">3#</a></li>
    </ul>
</div>
<aside>

</aside>
<article>

</article>

<script type="text/html" id="tpl_news">
<section data-schema-event="news">
    <h1>News</h1>
    <ul>
        <li><a href="javascript:;" data-schema-news="">article1#</a></li>
        <li><a href="javascript:;" data-schema-news="">article2#</a></li>
        <li><a href="javascript:;" data-schema-news="">article3#</a></li>
    </ul>
</section>
</script>
<script type="text/html" id="tpl_article">
    <h3>Article</h3>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
    quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
    consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
    proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</script>
<script type="text/javascript">
    schema.list=function (event,options) {
        $(schema.events.list.selector).on('click',function(){
            $('aside').html($('#tpl_news').html());
            schema.trigger('news');
        });
    }
    schema.news=function (event,options) {
        $('article').html($('#tpl_article').html());
    }
</script>
```

**Comment by photino** [comment]
@lann1986 这个例子中，在使用`data-schema-event="news"`定义事件时，`schema.news()`就已经被自动调用过一次了，然后在点击`[data-schema-list]`时又会被调用
